In [1]:
import pandas as pd

In [99]:
df=pd.read_excel(r"C:\Users\saiki\Downloads\Sales.project1.xlsx")
df.head()

   Order_id  Order_date  Customer_id Region     Product    Cost    Sales
0         1  2023-05-23       9346.0    NaN         NaN     NaN      NaN
1         2  2023-03-31       4973.0  South    Keyboard  675.54  1070.48
2         3  2023-03-22       8149.0  South         NaN  277.49   663.97
3         4  2023-01-18       6317.0   East  Headphones  352.82   745.75
4         5  2023-10-01       6141.0  South    Keyboard  729.79  1149.35

In [101]:
df

       Order_id  Order_date  Customer_id Region     Product    Cost    Sales
0             1  2023-05-23       9346.0    NaN         NaN     NaN      NaN
1             2  2023-03-31       4973.0  South    Keyboard  675.54  1070.48
2             3  2023-03-22       8149.0  South         NaN  277.49   663.97
3             4  2023-01-18       6317.0   East  Headphones  352.82   745.75
4             5  2023-10-01       6141.0  South    Keyboard  729.79  1149.35
...         ...         ...          ...    ...         ...     ...      ...
49995     49996  2023-01-05       1724.0    NaN    Keyboard  230.01   532.99
49996     49997  2023-09-25       7686.0   West      Tablet  436.17   748.44
49997     49998  2023-07-10       8577.0  South    Keyboard  529.42   995.57
49998     49999  2023-09-22       6986.0  North     Monitor  516.65   656.95
49999     50000  2023-10-07       4922.0  North    Keyboard  411.04   781.67

[50000 rows x 7 columns]

In [104]:
#remove duplicates
df=df.drop_duplicates()

In [105]:
df

       Order_id  Order_date  Customer_id Region     Product    Cost    Sales
0             1  2023-05-23       9346.0    NaN         NaN     NaN      NaN
1             2  2023-03-31       4973.0  South    Keyboard  675.54  1070.48
2             3  2023-03-22       8149.0  South         NaN  277.49   663.97
3             4  2023-01-18       6317.0   East  Headphones  352.82   745.75
4             5  2023-10-01       6141.0  South    Keyboard  729.79  1149.35
...         ...         ...          ...    ...         ...     ...      ...
49995     49996  2023-01-05       1724.0    NaN    Keyboard  230.01   532.99
49996     49997  2023-09-25       7686.0   West      Tablet  436.17   748.44
49997     49998  2023-07-10       8577.0  South    Keyboard  529.42   995.57
49998     49999  2023-09-22       6986.0  North     Monitor  516.65   656.95
49999     50000  2023-10-07       4922.0  North    Keyboard  411.04   781.67

[50000 rows x 7 columns]

In [106]:
df.isnull().sum()

Order_id          0
Order_date     2455
Customer_id    2505
Region         2556
Product        2518
Cost           2552
Sales          4878
dtype: int64

In [107]:
df=df.dropna()

In [108]:
df=df.drop_duplicates()

In [109]:
df

       Order_id  Order_date  Customer_id Region     Product    Cost    Sales
1             2  2023-03-31       4973.0  South    Keyboard  675.54  1070.48
3             4  2023-01-18       6317.0   East  Headphones  352.82   745.75
4             5  2023-10-01       6141.0  South    Keyboard  729.79  1149.35
6             7  2023-08-27       2205.0  South    Keyboard  393.45   405.31
7             8  2023-04-28       1277.0   East      Tablet  214.77   570.89
...         ...         ...          ...    ...         ...     ...      ...
49990     49991  2023-09-23       1957.0  North      Laptop  930.80  1167.33
49996     49997  2023-09-25       7686.0   West      Tablet  436.17   748.44
49997     49998  2023-07-10       8577.0  South    Keyboard  529.42   995.57
49998     49999  2023-09-22       6986.0  North     Monitor  516.65   656.95
49999     50000  2023-10-07       4922.0  North    Keyboard  411.04   781.67

[36777 rows x 7 columns]

In [110]:
df['Order_date'] = pd.to_datetime(df['Order_date'], errors='coerce')

In [111]:
df=df.dropna(subset=['Order_date'])

In [112]:
df

       Order_id Order_date  Customer_id Region     Product    Cost    Sales
1             2 2023-03-31       4973.0  South    Keyboard  675.54  1070.48
3             4 2023-01-18       6317.0   East  Headphones  352.82   745.75
4             5 2023-10-01       6141.0  South    Keyboard  729.79  1149.35
6             7 2023-08-27       2205.0  South    Keyboard  393.45   405.31
7             8 2023-04-28       1277.0   East      Tablet  214.77   570.89
...         ...        ...          ...    ...         ...     ...      ...
49990     49991 2023-09-23       1957.0  North      Laptop  930.80  1167.33
49996     49997 2023-09-25       7686.0   West      Tablet  436.17   748.44
49997     49998 2023-07-10       8577.0  South    Keyboard  529.42   995.57
49998     49999 2023-09-22       6986.0  North     Monitor  516.65   656.95
49999     50000 2023-10-07       4922.0  North    Keyboard  411.04   781.67

[36777 rows x 7 columns]

In [113]:
df['Profit'] = df['Sales']-df['Cost']
df['Year']=df['Order_date'].dt.year
df['Month']=df['Order_date'].dt.month

In [114]:
df

,Order_id,Order_date,Customer_id,Region,Product,Cost,Sales,Profit,Year,Month
1,2,2023-03-31,4973.0,South,Keyboard,675.54,1070.48,394.94,2023,3
3,4,2023-01-18,6317.0,East,Headphones,352.82,745.75,392.93,2023,1
4,5,2023-10-01,6141.0,South,Keyboard,729.79,1149.35,419.56,2023,10
6,7,2023-08-27,2205.0,South,Keyboard,393.45,405.31,11.86,2023,8
7,8,2023-04-28,1277.0,East,Tablet,214.77,570.89,356.12,2023,4
...,...,...,...,...,...,...,...,...,...,...
49990,49991,2023-09-23,1957.0,North,Laptop,930.80,1167.33,236.53,2023,9
49996,49997,2023-09-25,7686.0,West,Tablet,436.17,748.44,312.27,2023,9
49997,49998,2023-07-10,8577.0,South,Keyboard,529.42,995.57,466.15,2023,7
49998,49999,2023-09-22,6986.0,North,Monitor,516.65,656.95,140.30,2023,9
49999,50000,2023-10-07,4922.0,North,Keyboard,411.04,781.67,370.63,2023,10

In [115]:
df.to_csv('sales_clean.csv',index=False)

In [116]:
import pandas as pd
from sqlalchemy import create_engine

In [117]:
df = pd.read_csv('sales_clean.csv')

In [118]:
df

,Order_id,Order_date,Customer_id,Region,Product,Cost,Sales,Profit,Year,Month
0,2,2023-03-31,4973.0,South,Keyboard,675.54,1070.48,394.94,2023,3
1,4,2023-01-18,6317.0,East,Headphones,352.82,745.75,392.93,2023,1
2,5,2023-10-01,6141.0,South,Keyboard,729.79,1149.35,419.56,2023,10
3,7,2023-08-27,2205.0,South,Keyboard,393.45,405.31,11.86,2023,8
4,8,2023-04-28,1277.0,East,Tablet,214.77,570.89,356.12,2023,4
...,...,...,...,...,...,...,...,...,...,...
36772,49991,2023-09-23,1957.0,North,Laptop,930.80,1167.33,236.53,2023,9
36773,49997,2023-09-25,7686.0,West,Tablet,436.17,748.44,312.27,2023,9
36774,49998,2023-07-10,8577.0,South,Keyboard,529.42,995.57,466.15,2023,7
36775,49999,2023-09-22,6986.0,North,Monitor,516.65,656.95,140.30,2023,9
36776,50000,2023-10-07,4922.0,North,Keyboard,411.04,781.67,370.63,2023,10

In [119]:
engine=create_engine('mysql+pymysql://root:mysql123@localhost:3306/salesdb')
df.head()
df.describe()

,Order_id,Customer_id,Cost,Sales,Profit,Year,Month
count,36777.000000,36777.000000,36777.000000,36777.000000,36777.000000,36777.000000,36777.000000
mean,25005.628164,5494.691900,547.778412,803.566302,255.787891,2023.003209,6.501210
std,14434.965241,2593.169254,260.241475,296.841533,141.578146,0.056554,3.450204
min,2.000000,1000.000000,100.020000,112.640000,10.000000,2023.000000,1.000000
25%,12429.000000,3233.000000,320.910000,577.380000,132.690000,2023.000000,4.000000
50%,25004.000000,5510.000000,546.650000,801.550000,256.670000,2023.000000,7.000000
75%,37480.000000,7719.000000,773.820000,1031.730000,379.210000,2023.000000,9.000000
max,50000.000000,9999.000000,999.970000,1495.960000,500.000000,2024.000000,12.000000

In [120]:
df = pd.read_csv('sales_clean.csv')
df

,Order_id,Order_date,Customer_id,Region,Product,Cost,Sales,Profit,Year,Month
0,2,2023-03-31,4973.0,South,Keyboard,675.54,1070.48,394.94,2023,3
1,4,2023-01-18,6317.0,East,Headphones,352.82,745.75,392.93,2023,1
2,5,2023-10-01,6141.0,South,Keyboard,729.79,1149.35,419.56,2023,10
3,7,2023-08-27,2205.0,South,Keyboard,393.45,405.31,11.86,2023,8
4,8,2023-04-28,1277.0,East,Tablet,214.77,570.89,356.12,2023,4
...,...,...,...,...,...,...,...,...,...,...
36772,49991,2023-09-23,1957.0,North,Laptop,930.80,1167.33,236.53,2023,9
36773,49997,2023-09-25,7686.0,West,Tablet,436.17,748.44,312.27,2023,9
36774,49998,2023-07-10,8577.0,South,Keyboard,529.42,995.57,466.15,2023,7
36775,49999,2023-09-22,6986.0,North,Monitor,516.65,656.95,140.30,2023,9
36776,50000,2023-10-07,4922.0,North,Keyboard,411.04,781.67,370.63,2023,10

In [121]:
df.to_sql('sales_data1', con=engine, if_exists='replace', index=False)

36777